//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.nebby1999.nebula:InputActionGUIDCodeGenerator
//     version 1.0.0
//     from Assets/ACInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine.InputSystem;
namespace AC
{
    public class ACInputActionGUIDS
    {
        // HQMap
        public static readonly Guid hQMapGUID = Guid.Parse("4ee71c52-ea80-47e1-9185-6c4e15a41e56");
        public class HQMap
        {
            public static readonly Guid switchToBattleState1GUID = Guid.Parse("773f83dd-939c-4194-a07a-0d84fdb41add");
            public static readonly Guid switchToBattleState2GUID = Guid.Parse("c1bfa46d-bb4b-492f-9df9-b59cc1ace797");
            public static readonly Guid redResourceToBase1GUID = Guid.Parse("4f2ac04e-6e15-4438-950c-eb4444d0046a");
            public static readonly Guid redResourceRestGUID = Guid.Parse("4870caf8-d799-4027-96fe-e3229388d20e");
            public static readonly Guid redResourceToBase2GUID = Guid.Parse("62584c5e-ad51-494a-b392-1a3615919049");
            public static readonly Guid blackResourceToBase1GUID = Guid.Parse("db4f9448-caef-4529-87a3-5c1e784dcf46");
            public static readonly Guid blackResourceToRestGUID = Guid.Parse("7c982f6a-f67f-48c3-b46b-91d94db8e4f1");
            public static readonly Guid blackResourceToBase2GUID = Guid.Parse("a02f2dc0-055c-4e4d-8d62-6ed81e9ecb50");
            private HQMap() {}
        }
        // VehicleMap
        public static readonly Guid vehicleMapGUID = Guid.Parse("50dd9d08-ff15-48b7-8b42-1f89518d302e");
        public class VehicleMap
        {
            public static readonly Guid dissipateHeatGUID = Guid.Parse("cadc9f28-2ea5-4aea-842a-82e5b9667888");
            public static readonly Guid harvest_ShootGUID = Guid.Parse("8a010eab-8a1f-488a-96e6-c47bd77b2835");
            public static readonly Guid decoy_StunGUID = Guid.Parse("27d93b74-46df-4424-a6b5-a8309b36a5c9");
            public static readonly Guid leftTrackGUID = Guid.Parse("aa958129-960e-4cda-bb06-415a9c6f74ea");
            public static readonly Guid rightTrackGUID = Guid.Parse("b38a3d55-e717-42a6-98d0-aa63192b8c33");
            private VehicleMap() {}
        }
        private ACInputActionGUIDS() {}
    }
}
