//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.nebby1999.nebula:GameTagsCodeGenerator
//     version 1.0.0
//     from ProjectSettings
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC
{
    public struct GameTags
    {
        public const string UNTAGGED = "Untagged";
        public const string RESPAWN = "Respawn";
        public const string FINISH = "Finish";
        public const string EDITOR_ONLY = "EditorOnly";
        public const string MAIN_CAMERA = "MainCamera";
        public const string PLAYER = "Player";
        public const string GAME_CONTROLLER = "GameController";
        public const string H_Q_TEAM = "HQTeam";
        public const string ENEMY_TEAM = "EnemyTeam";
    }
}
