using System.IO;
using System.Text;

namespace Nebula.Editor.CodeGenerators
{
    public static class LayerIndexCodeGenerator
    {
        public static bool GenerateCode(NebulaSettings.LayerIndexData data)
        {
            if(!Path.HasExtension(data.filePath))
            {
                data.filePath += ".cs";
            }

            StringBuilder stringBuilder = new StringBuilder();
            using (CodeGeneratorHelper helper = new CodeGeneratorHelper())
            {
                stringBuilder.Append(helper.MakeAutoGeneratedCodeHeader("Nebula.LayerIndexCodeGenerator", "1.0.0"));
            }
            stringBuilder.Append(
@"using System;
using UnityEngine");
            var validationData = new CodeGeneratorValidator.ValidationData
            {
                code = stringBuilder,
                desiredOutputPath = data.filePath
            };

            return CodeGeneratorValidator.Validate(validationData);
        }
    }
}